import"./assets/modulepreload-polyfill-3cfb730f.js";/* empty css                                  */function i(){return fetch("http://localhost:3000/users").then(r=>r.json())}function l(e){const r="http://localhost:3000/users",o={method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(e)};return fetch(r,o).then(n=>n.json())}function m({id:e,...t}){const o=`http://localhost:3000/users/${e}`,n={method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(t)};return fetch(o,n).then(u=>u.json())}function d({id:e,...t}){const o=`http://localhost:3000/users/${e}`,n={method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(t)};return fetch(o,n).then(u=>u.json())}function p(e){const r=`http://localhost:3000/users/${e}`;return fetch(r,{method:"DELETE"}).then(n=>n.json())}const a={userListElem:document.querySelector(".users-cards"),createUserForm:document.querySelector(".create-user"),updateUserForm:document.querySelector(".update-user"),resetUserForm:document.querySelector(".rewrite-user"),deleteUserForm:document.querySelector(".delete-user")};a.createUserForm.addEventListener("submit",U);a.resetUserForm.addEventListener("submit",E);a.updateUserForm.addEventListener("submit",f);a.deleteUserForm.addEventListener("submit",D);function c(e){return`<li class="user-card" data-id="${e.id}">
        <img             
            src='https://source.unsplash.com/720x1280/?random=${e.id}&girl,portret, celebrity' alt="#"
            class="user-avatar" >
        <h3 class="user-title">${e.name}</h3>
         <p class="contact-item">Phone: ${e.phone}</p>
         <p class="contact-item">Email: ${e.email}</p>
         <button class="btn-delete" type="button">Delete</button>
        </li>`}function h(e){return e.map(c).join("")}i().then(e=>{const t=h(e);a.userListElem.innerHTML=t});function U(e){e.preventDefault();const t={name:a.createUserForm.elements.userName.value.trim(),phone:a.createUserForm.elements.userPhone.value.trim(),email:a.createUserForm.elements.userEmail.value.trim(),img:"https://source.unsplash.com/720x1280/?random=${Math.random()}&girl,portret, celebrity"};l(t).then(s=>{const r=c(s);a.userListElem.insertAdjacentHTML("afterbegin",r)}),e.target.reset()}function E(e){e.preventDefault();const t=new FormData(a.resetUserForm),s={};t.forEach((r,o)=>{s[o]=r}),d(s).then(r=>{const o=c(r),n=document.querySelector(`[data-id="${s.id}"]`);n.insertAdjacentHTML("afterend",o),n.remove()}),e.target.reset()}function f(e){e.preventDefault();const t={};new FormData(a.updateUserForm).forEach((r,o)=>{r&&(t[o]=r)}),m(t).then(r=>{const o=c(r),n=document.querySelector(`[data-id="${t.id}"]`);n.insertAdjacentHTML("afterend",o),n.remove()}),e.target.reset()}function D(e){e.preventDefault();const t=a.deleteUserForm.elements.userId.value;p(t).then(()=>{document.querySelector(`[data-id="${t}"]`).remove()}).catch(s=>{console.log(s)}),e.target.reset()}
//# sourceMappingURL=commonHelpers8.js.map
